# endpoint: https://druid.datalegend.net/dataLegend/CEDAR-S/sparql/CEDAR-S
# replace 1869 for 1879, 1889, 1899 or 1909

PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cedar: <http://lod.cedar-project.nl:8888/cedar/resource/>
PREFIX maritalstatus: <http://lod.cedar-project.nl/vocab/cedar-maritalstatus#>
PREFIX sdmx-dimension: <http://purl.org/linked-data/sdmx/2009/dimension#>
PREFIX sdmx-code: <http://purl.org/linked-data/sdmx/2009/code#>
PREFIX cedarterms: <http://lod.cedar-project.nl/vocab/cedar#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX gg: <http://www.gemeentegeschiedenis.nl/amco/>

SELECT ?obs ?pop WHERE {
	?obs a qb:Observation.
	?obs sdmx-dimension:refArea gg:11150 .
	?obs cedarterms:population ?pop.
	?slice a qb:Slice.
	?slice qb:observation ?obs.
  ?slice sdmx-dimension:refPeriod "1869"^^xsd:integer.
	FILTER (NOT EXISTS {?obs cedarterms:isTotal ?total })
}
